# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-watchman` gem.
# Please instead update this file by running `bin/tapioca gem ruby-watchman`.


module RubyWatchman
  class << self
    def dump(_arg0); end
    def load(_arg0); end
    def query(_arg0, _arg1); end
  end
end
