# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Asciidoctor; end
module ::Nokogiri; end
module HelloString::Error; end
module Oscal::AssessmentResult::AssessmentResult; end
module Oscal::ImportAP; end
module Oscal::InsertControl::ExcludeControls; end
module Oscal::OscalDatatype::UuidDataType; end
